const $=id=>document.getElementById(id);let timer;let demoMode=false;
const fmtMoney=n=>`$${Number(n||0).toFixed(n<.01?5:3)}`;
const fmtPct=n=>`${(Number(n||0)*100).toFixed(1)}%`;
const toast=m=>{$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)};
async function api(path){const token=$('token').value.trim();if(!token)throw new Error('请先输入管理令牌');const r=await fetch(path,{headers:{'X-Layman-Admin-Token':token},cache:'no-store'});if(!r.ok){let m=`HTTP ${r.status}`;try{m=(await r.json()).detail||m}catch{}throw new Error(m)}return r.json()}
function setStatus(ok,text){$('statusDot').className=ok?'ok':'bad';$('statusText').textContent=text}
function bars(routes,total){for(const tier of ['fast','balanced','deep']){const n=routes[tier]||0;$(tier+'N').textContent=n;$(tier+'Bar').style.width=`${total?n/total*100:0}%`}}
function renderSummary(s){$('savings').textContent=`${Number(s.estimated_savings_percent||0).toFixed(1)}%`;$('savingUsd').textContent=`估算 ${fmtMoney(s.estimated_savings_usd)} · 非实测`;$('requests').textContent=Number(s.total_requests||0).toLocaleString();$('tokens').textContent=`${Number((s.input_tokens||0)+(s.output_tokens||0)).toLocaleString()} tokens · 缓存读 ${Number(s.cached_tokens||0).toLocaleString()} / 写 ${Number(s.cache_write_tokens||0).toLocaleString()}`;$('latency').textContent=`${Math.round(s.average_latency_ms||0)} ms`;$('fallback').textContent=fmtPct(s.fallback_rate);$('quality').textContent=`质量通过率 ${s.validator_pass_rate==null?'—':fmtPct(s.validator_pass_rate)}`;$('priceVersion').textContent=s.price_version||'—';bars(s.routes||{},s.total_requests||0);const a=Number(s.total_cost_usd||0),b=Number(s.estimated_always_deep_cost_usd||0),max=Math.max(a,b,.000001);$('actualCost').style.width=`${a/max*100}%`;$('baselineCost').style.width=`${b/max*100}%`;$('actualCostLabel').textContent=fmtMoney(a);$('baselineCostLabel').textContent=fmtMoney(b)}
function renderRecent(rows){$('recent').innerHTML=rows.length?rows.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString()}</td><td>${r.task_type}</td><td><span class="risk-tag">${r.risk}</span></td><td><span class="route-tag ${r.route_tier}">${r.route_tier}</span></td><td>${Number(r.input_tokens+r.output_tokens).toLocaleString()}</td><td>${r.latency_ms} ms</td><td>${fmtMoney(r.estimated_cost_usd)}</td><td>${r.error_category?'ERROR':r.fallback_used?'FALLBACK':'OK'}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">还没有遥测数据</td></tr>'}
async function refresh(){try{const [s,r]=await Promise.all([api('/admin/usage/summary'),api('/admin/usage/recent?limit=30')]);renderSummary(s);renderRecent(r.requests);setStatus(true,demoMode?'演示模式 · 合成数据':'路由器在线');sessionStorage.setItem('layman-admin-token',$('token').value);clearInterval(timer);timer=setInterval(refresh,15000)}catch(e){setStatus(false,'需要连接');toast(e.message);clearInterval(timer)}}
$('connect').addEventListener('click',refresh);$('refresh').addEventListener('click',refresh);$('token').addEventListener('keydown',e=>{if(e.key==='Enter')refresh()});$('token').value=sessionStorage.getItem('layman-admin-token')||'';fetch('/healthz').then(r=>r.json()).then(h=>{demoMode=Boolean(h.demo_mode);setStatus(true,demoMode?'演示模式 · 待认证':'服务在线 · 待认证')}).catch(()=>setStatus(false,'服务离线'));if($('token').value)refresh();
